# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

app_name = "CSSDKDemo"


fastlane_version "1.99.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    #carthage
  end

  lane :betatest do
    changelog = prompt(
      text: "Co se má otestovat?: ",
      multi_line_end_keyword: "END"
    )
    increment_build_number
    gym scheme: "DevCSSDKTestApp",
        clean:true,
        use_legacy_build_api: true,
        export_method: "ad-hoc",
        output_name: app_name,
        output_directory: "./build"
    hockey(
      api_token: ENV['CSAS_HOCKEY_API_TOKEN'],
      ipa: "./build/#{app_name}.ipa",
      notes: "Co se má otestovat?: \n #{changelog}"
    )
  end


  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
